# Change these first
owner: NehalDamania # Your GitHub organization or username, where this repository lives
repo: becpl-uptime # The name of this repository

sites:
  - name: Becpl Angular UI
    url: $BECPL_ANGULAR_URL
  - name: Becpl Auth
    url: $BECPL_KEYCLOAK_URL
  - name: Becpl
    url: $BECPL_URL

assignees: # Users to assign downtime issues (optional)
  - NehalDamania
  - lakhi
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /becpl-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Becpl Uptime
  introTitle: "This page is used to monitor the uptimes of various becpl services."
  introMessage: Uptime Status for the servers is as below
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
